version: '3.8'

services:
  web:
    build: .                 
    ports:
      - "5000:5000"            
    depends_on:
      - db                       
    env_file:
      - .env               

  db:
    image: postgres:latest     
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}    
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data:                       
